/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.26                          *
*        Compiled Aug  8 2014, 14:49:54                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "usart.h"
#include "ChooseTheGarageDLG.h"
#include "string.h"
#include "led.h"
#include "Speech_control.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0 (GUI_ID_USER + 0x00)
#define ID_BUTTON_0 (GUI_ID_USER + 0x01)
#define ID_RADIO_0 (GUI_ID_USER + 0x02)
#define ID_TEXT_0 (GUI_ID_USER + 0x03)
#define ID_BUTTON_1 (GUI_ID_USER + 0x04)
#define ID_TEXT_1 (GUI_ID_USER + 0x05)
#define ID_TEXT_2 (GUI_ID_USER + 0x06)
#define ID_TEXT_3 (GUI_ID_USER + 0x07)
#define ID_TEXT_4 (GUI_ID_USER + 0x08)
#define ID_TEXT_5 (GUI_ID_USER + 0x09)
#define ID_TEXT_6 (GUI_ID_USER + 0x0B)
#define ID_TEXT_7 (GUI_ID_USER + 0x0C)
#define ID_TEXT_8 (GUI_ID_USER + 0x0D)
#define ID_TEXT_9 (GUI_ID_USER + 0x0E)
#define ID_PROGBAR_0 (GUI_ID_USER + 0x11)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "ChooseTheGarage", ID_FRAMEWIN_0, 0, 0, 800, 480, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "OK", ID_BUTTON_0, 257, 220, 100, 50, 0, 0x0, 0 },
  { RADIO_CreateIndirect, "Radio", ID_RADIO_0, 22, 48, 145, 360, 0, 0x4106, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 15, 3, 380, 34, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "Cancel", ID_BUTTON_1, 260, 300, 100, 50, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_1, 213, 58, 249, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_2, 187, 91, 181, 31, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_3, 188, 121, 201, 27, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_4, 2, 407, 383, 25, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_5, 182, 150, 181, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_6, 410, 153, 368, 33, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_7, 410, 257, 374, 32, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_8, 410, 355, 376, 41, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_9, 414, 22, 362, 30, 0, 0x64, 0 },
  { PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_0, 387, -4, 20, 445, 1, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
char Garage;
char Garage_oid;
char Cancel_key_static = 0;
char start_static = 0;//¿ªÊ¼×´Ì¬
extern u8 CollisionValue;
extern u16 ParkingDurationS;
extern u16 ParkingFeeRMB; 


WM_HWIN update_hItem;


static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'ChooseTheGarage'
    //
  
    hItem = pMsg->hWin;
	update_hItem = hItem;
    FRAMEWIN_SetText(hItem, "Auto park system - Control center ");
    FRAMEWIN_SetFont(hItem, GUI_FONT_32_ASCII);
    FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'OK'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, GUI_FONT_24_ASCII);
    //
    // Initialization of 'Radio'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_RADIO_0);
    RADIO_SetText(hItem, "Garage 1", 0);
    RADIO_SetFont(hItem, GUI_FONT_32B_ASCII);
    RADIO_SetText(hItem, "Garage 2", 1);
    RADIO_SetText(hItem, "Garage 3", 2);
    RADIO_SetText(hItem, "Garage 4", 3);
    RADIO_SetText(hItem, "Garage 5", 4);
    RADIO_SetText(hItem, "Garage 6", 5);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_24_ASCII);
    TEXT_SetText(hItem, "Please select the corresponding garage ");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_TOP);
    TEXT_SetTextColor(hItem, 0x00FF0000);
    //
    // Initialization of 'Cancel'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetText(hItem, "Reset");
    BUTTON_SetFont(hItem, GUI_FONT_24_ASCII);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, GUI_FONT_24_ASCII);
    TEXT_SetText(hItem, "To start running, ");
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem, GUI_FONT_24_ASCII);
    TEXT_SetText(hItem, "click OK;Return to ");
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetText(hItem, "the home page and");
    TEXT_SetFont(hItem, GUI_FONT_24_ASCII);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetFont(hItem, GUI_FONT_20B_ASCII);
    TEXT_SetText(hItem, "The currently selected garage number is 1 ");
    TEXT_SetTextColor(hItem, 0x000000FF);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetFont(hItem, GUI_FONT_24_ASCII);
    TEXT_SetText(hItem, " click Cancel.");
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetFont(hItem, GUI_FONT_32B_ASCII);
    TEXT_SetText(hItem, "Parking Duration(S):");
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
    TEXT_SetFont(hItem, GUI_FONT_32B_ASCII);
    TEXT_SetText(hItem, "Parking fee  (RMB)  :");
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
    TEXT_SetFont(hItem, GUI_FONT_32B_ASCII);
    TEXT_SetText(hItem, "Collision times        :");
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
    TEXT_SetTextColor(hItem, 0x000000FF);
    TEXT_SetText(hItem, " wait tang wa user");
    TEXT_SetFont(hItem, GUI_FONT_24_1);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
	
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'OK'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
		  ParkingFeeRMB = 0;
		  ParkingDurationS = 0;
		  CollisionValue = 0;
		  hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
		  Speech_null();
		  switch(Garage)
		  {
			  case 0:
				  TEXT_SetText(hItem, "Entering garage No. 1 ");
				  LED1=1;LED2=0;LED3=0;LED4=0;LED5=0;LED6=0;
				  break;
			  case 1:
				  TEXT_SetText(hItem, "Entering garage No. 2 ");
			      LED1=0;LED2=1;LED3=0;LED4=0;LED5=0;LED6=0;
				  break;
			  case 2:
				  TEXT_SetText(hItem, "Entering garage No. 3 ");
			      LED1=0;LED2=0;LED3=1;LED4=0;LED5=0;LED6=0;
				  break;
			  case 3:
				  TEXT_SetText(hItem, "Entering garage No. 4 ");
			      LED1=0;LED2=0;LED3=0;LED4=1;LED5=0;LED6=0;
				  break;
			  case 4:
				  TEXT_SetText(hItem, "Entering garage No. 5 ");
			      LED1=0;LED2=0;LED3=0;LED4=0;LED5=1;LED6=0;
				  break;
			  case 5:
				  TEXT_SetText(hItem, "Entering garage No. 6 ");
			      LED1=0;LED2=0;LED3=0;LED4=0;LED5=0;LED6=1;
				  break;
			  default:
				  break;
		  }
		  
		  if(Garage<=5)
		  {
			//·¢ËÍ
			USART1Send(0x55);
			USART1Send(0x01);
			USART1Send(0x00);
			USART1Send(Garage+0x01);
			USART1Send((u8)(Garage+0x01+0x01+0x00));
			USART1Send(0xAA);
		  }
		  start_static = 1;
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_RADIO_0: // Notifications sent by 'Radio'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
		  hItem = WM_GetDialogItem(pMsg->hWin, ID_RADIO_0);
		  Garage = RADIO_GetValue(hItem);
		  hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
		  if(Garage_oid!=Garage)
		  {
			 Garage_oid= Garage;
			Speech_SwitchGarage(Garage+1);
		  }
		  switch(Garage)
		  {
			  case 0:
				  TEXT_SetText(hItem, "The currently selected garage number is 1 ");
				  break;
			  case 1:
				  TEXT_SetText(hItem, "The currently selected garage number is 2 ");
				  break;
			  case 2:
				  TEXT_SetText(hItem, "The currently selected garage number is 3 ");
				  break;
			  case 3:
				  TEXT_SetText(hItem, "The currently selected garage number is 4 ");
				  break;
			  case 4:
				  TEXT_SetText(hItem, "The currently selected garage number is 5 ");
				  break;
			  case 5:
				  TEXT_SetText(hItem, "The currently selected garage number is 6 ");
				  break;
		  }
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Cancel'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
		  Cancel_key_static = 1;
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateChooseTheGarage
*/
WM_HWIN CreateChooseTheGarage(void);
WM_HWIN CreateChooseTheGarage(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/

void updateDialogBox(void)
{
	WM_HWIN hItem;
	u8 temp[30] = "Tang wa"; 
	u8 value[3] = "   ";
	if(start_static == 1)
	{
		strcpy((char*)temp,"Parking Duration(S):");
		if(ParkingDurationS < 10)
		{
			value[0] = ' ';
			value[1] = ' ';
			value[2] = ParkingDurationS+'0';				
		}else if(ParkingDurationS < 100)
		{
			value[0] = ' ';
			value[1] = ParkingDurationS/10+'0';
			value[2] = ParkingDurationS%10+'0';			
		}else
		{
			value[0] = ParkingDurationS/100+'0';
			value[1] = ParkingDurationS/10%10+'0';
			value[2] = ParkingDurationS%10%10+'0';
		}
		strcat((char*)temp,(char*)value);
		hItem = WM_GetDialogItem(update_hItem, ID_TEXT_6);
		TEXT_SetText(hItem, (char*)temp);

		
		strcpy((char*)temp,"Parking fee  (RMB)  :");
		if(ParkingFeeRMB < 10)
		{
			value[0] = ' ';
			value[1] = ' ';
			value[2] = ParkingFeeRMB+'0';				
		}else if(ParkingFeeRMB < 100)
		{
			value[0] = ' ';
			value[1] = ParkingFeeRMB/10+'0';
			value[2] = ParkingFeeRMB%10+'0';			
		}else
		{
			value[0] = ParkingFeeRMB/100+'0';
			value[1] = ParkingFeeRMB/10%10+'0';
			value[2] = ParkingFeeRMB%10%10+'0';
		}
		strcat((char*)temp,(char*)value);
		hItem = WM_GetDialogItem(update_hItem, ID_TEXT_7);
		TEXT_SetText(hItem, (char*)temp);

		strcpy((char*)temp,"Collision times        :");
		if(CollisionValue < 10)
		{
			value[0] = ' ';
			value[1] = ' ';
			value[2] = CollisionValue+'0';				
		}else if(CollisionValue < 100)
		{
			value[0] = ' ';
			value[1] = CollisionValue/10+'0';
			value[2] = CollisionValue%10+'0';			
		}else
		{
			value[0] = CollisionValue/100+'0';
			value[1] = CollisionValue/10%10+'0';
			value[2] = CollisionValue%10%10+'0';
		}
		strcat((char*)temp,(char*)value);
		
		hItem = WM_GetDialogItem(update_hItem, ID_TEXT_8);
		TEXT_SetText(hItem, (char*)temp);
	}
}


